# Generated by Django 2.1.11 on 2020-04-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('filename', models.CharField(default='', max_length=100)),
                ('is_sl', models.BooleanField(default=False)),
                ('sl', models.BooleanField()),
                ('dj', models.CharField(max_length=10)),
                ('zxr', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('jf', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sug',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
